# - Find pthread
# Find the native PTHREAD includes and library
#
#  PTHREAD_INCLUDE_DIR - where to find pthread.h, etc.
#  PTHREADLIBRARIES   - List of libraries when using pthread.
#  PTHREADS_FOUND       - True if pthreads found.


IF (PTHREAD_INCLUDE_DIR)
  # Already in cache, be silent
  SET(PTHREAD_FIND_QUIETLY TRUE)
ENDIF (PTHREAD_INCLUDE_DIR)

FIND_PATH(PTHREAD_INCLUDE_DIR pthread.h
  /usr/local/include
  /usr/include
  /opt/local/include
)

SET(PTHREAD_NAMES pthread)
FIND_LIBRARY(PTHREAD_LIBRARY
  NAMES ${PTHREAD_NAMES}
  PATHS /usr/lib /usr/local/lib /opt/local/lib
)

IF (PTHREAD_INCLUDE_DIR AND PTHREAD_LIBRARY)
   SET(PTHREAD_FOUND TRUE)
    SET( PTHREAD_LIBRARIES ${PTHREAD_LIBRARY} )
ELSE (PTHREAD_INCLUDE_DIR AND PTHREAD_LIBRARY)
   SET(PTHREAD_FOUND FALSE)
   SET( PTHREAD_LIBRARIES )
ENDIF (PTHREAD_INCLUDE_DIR AND PTHREAD_LIBRARY)

IF (PTHREAD_FOUND)
   IF (NOT PTHREAD_FIND_QUIETLY)
      MESSAGE(STATUS "Found PTHREAD: ${PTHREAD_LIBRARY}")
   ENDIF (NOT PTHREAD_FIND_QUIETLY)
ELSE (PTHREAD_FOUND)
   IF (PTHREAD_FIND_REQUIRED)
      MESSAGE(STATUS "Looked for pthread libraries named ${PTHREADS_NAMES}.")
      MESSAGE(FATAL_ERROR "Could NOT find pthread library")
   ENDIF (PTHREAD_FIND_REQUIRED)
ENDIF (PTHREAD_FOUND)

MARK_AS_ADVANCED(
  PTHREAD_LIBRARY
  PTHREAD_INCLUDE_DIR
)
