# - Find ncurses
# Find the native NCURSES includes and library
#
#  NCURSES_INCLUDE_DIR - where to find ncurses.h, etc.
#  NCURSES_LIBRARIES   - List of libraries when using ncurses.
#  NCURSES_FOUND       - True if ncurses found.


IF (NCURSES_INCLUDE_DIR)
  # Already in cache, be silent
  SET(NCURSES_FIND_QUIETLY TRUE)
ENDIF (NCURSES_INCLUDE_DIR)

FIND_PATH(NCURSES_INCLUDE_DIR ncurses.h
  /usr/local/include
  /usr/include
  /opt/local/include
)

SET(NCURSES_NAMES ncurses)
FIND_LIBRARY(NCURSES_LIBRARY
  NAMES ${NCURSES_NAMES}
  PATHS /usr/lib /usr/local/lib /opt/local/lib
)

IF (NCURSES_INCLUDE_DIR AND NCURSES_LIBRARY)
   SET(NCURSES_FOUND TRUE)
    SET( NCURSES_LIBRARIES ${NCURSES_LIBRARY} )
ELSE (NCURSES_INCLUDE_DIR AND NCURSES_LIBRARY)
   SET(NCURSES_FOUND FALSE)
   SET( NCURSES_LIBRARIES )
ENDIF (NCURSES_INCLUDE_DIR AND NCURSES_LIBRARY)

IF (NCURSES_FOUND)
   IF (NOT NCURSES_FIND_QUIETLY)
      MESSAGE(STATUS "Found NCURSES: ${NCURSES_LIBRARY}")
   ENDIF (NOT NCURSES_FIND_QUIETLY)
ELSE (NCURSES_FOUND)
   IF (NCURSES_FIND_REQUIRED)
      MESSAGE(STATUS "Looked for ncurses libraries named ${NCURSESS_NAMES}.")
      MESSAGE(FATAL_ERROR "Could NOT find ncurses library")
   ENDIF (NCURSES_FIND_REQUIRED)
ENDIF (NCURSES_FOUND)

MARK_AS_ADVANCED(
  NCURSES_LIBRARY
  NCURSES_INCLUDE_DIR
)
